//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_Tovar { get; set; }
        public string NameTovar { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID_Sklad { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
